version: "2"
services:
  mariadb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
  presto:
    image: ahanaio/prestodb-sandbox:0.235
    ports:
    - 8080:8080
    volumes:
     - ./etc/s3.properties:/opt/presto-server/etc/catalog/s3.properties
     - ./etc/jvm.config:/opt/presto-server/etc/jvm.config
  hive:
    build: hive
    environment:
      DB_URI: mariadb:3306
    depends_on:
      - mariadb
